/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["ApiHealthHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stories */
        get: operations["ApiStoriesListStories"];
        put?: never;
        /** Create a story */
        post: operations["ApiStoriesCreateStory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one story */
        get: operations["ApiStoriesStoryIdGetStory"];
        put?: never;
        post?: never;
        /** Delete a story */
        delete: operations["ApiStoriesStoryIdDeleteStory"];
        options?: never;
        head?: never;
        /** Update a story */
        patch: operations["ApiStoriesStoryIdUpdateStory"];
        trace?: never;
    };
    "/api/stories/{story_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Structural health findings */
        get: operations["ApiStoriesStoryIdHealthGetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Level readiness for a story */
        get: operations["ApiStoriesStoryIdLadderGetLadder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/scaffold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed acts and beats from the story's framework */
        post: operations["ApiStoriesStoryIdScaffoldScaffold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events in story-world order */
        get: operations["ApiStoriesStoryIdEventsListEvents"];
        put?: never;
        /** Create an event */
        post: operations["ApiStoriesStoryIdEventsCreateEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an event */
        get: operations["ApiStoriesStoryIdEventsEventIdGetEvent"];
        put?: never;
        post?: never;
        /** Delete an event */
        delete: operations["ApiStoriesStoryIdEventsEventIdDeleteEvent"];
        options?: never;
        head?: never;
        /** Update an event */
        patch: operations["ApiStoriesStoryIdEventsEventIdUpdateEvent"];
        trace?: never;
    };
    "/api/stories/{story_id}/acts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List acts in order */
        get: operations["ApiStoriesStoryIdActsListActs"];
        put?: never;
        /** Create an act */
        post: operations["ApiStoriesStoryIdActsCreateAct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/acts/{act_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an act */
        get: operations["ApiStoriesStoryIdActsActIdGetAct"];
        put?: never;
        post?: never;
        /** Delete an act */
        delete: operations["ApiStoriesStoryIdActsActIdDeleteAct"];
        options?: never;
        head?: never;
        /** Update an act */
        patch: operations["ApiStoriesStoryIdActsActIdUpdateAct"];
        trace?: never;
    };
    "/api/stories/{story_id}/beats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List beats in order */
        get: operations["ApiStoriesStoryIdBeatsListBeats"];
        put?: never;
        /** Create a beat */
        post: operations["ApiStoriesStoryIdBeatsCreateBeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/beats/{beat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a beat */
        get: operations["ApiStoriesStoryIdBeatsBeatIdGetBeat"];
        put?: never;
        post?: never;
        /** Delete a beat */
        delete: operations["ApiStoriesStoryIdBeatsBeatIdDeleteBeat"];
        options?: never;
        head?: never;
        /** Update a beat */
        patch: operations["ApiStoriesStoryIdBeatsBeatIdUpdateBeat"];
        trace?: never;
    };
    "/api/stories/{story_id}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List threads in order */
        get: operations["ApiStoriesStoryIdThreadsListThreads"];
        put?: never;
        /** Create a thread */
        post: operations["ApiStoriesStoryIdThreadsCreateThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a thread */
        get: operations["ApiStoriesStoryIdThreadsThreadIdGetThread"];
        put?: never;
        post?: never;
        /** Delete a thread */
        delete: operations["ApiStoriesStoryIdThreadsThreadIdDeleteThread"];
        options?: never;
        head?: never;
        /** Update a thread */
        patch: operations["ApiStoriesStoryIdThreadsThreadIdUpdateThread"];
        trace?: never;
    };
    "/api/stories/{story_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List characters */
        get: operations["ApiStoriesStoryIdCharactersListCharacters"];
        put?: never;
        /** Create a character */
        post: operations["ApiStoriesStoryIdCharactersCreateCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a character */
        get: operations["ApiStoriesStoryIdCharactersCharacterIdGetCharacter"];
        put?: never;
        post?: never;
        /** Delete a character */
        delete: operations["ApiStoriesStoryIdCharactersCharacterIdDeleteCharacter"];
        options?: never;
        head?: never;
        /** Update a character */
        patch: operations["ApiStoriesStoryIdCharactersCharacterIdUpdateCharacter"];
        trace?: never;
    };
    "/api/stories/{story_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List relationships */
        get: operations["ApiStoriesStoryIdRelationshipsListRelationships"];
        put?: never;
        /** Create a relationship */
        post: operations["ApiStoriesStoryIdRelationshipsCreateRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a relationship */
        get: operations["ApiStoriesStoryIdRelationshipsRelationshipIdGetRelationship"];
        put?: never;
        post?: never;
        /** Delete a relationship */
        delete: operations["ApiStoriesStoryIdRelationshipsRelationshipIdDeleteRelationship"];
        options?: never;
        head?: never;
        /** Update a relationship */
        patch: operations["ApiStoriesStoryIdRelationshipsRelationshipIdUpdateRelationship"];
        trace?: never;
    };
    "/api/stories/{story_id}/arcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List arcs */
        get: operations["ApiStoriesStoryIdArcsListArcs"];
        put?: never;
        /** Create an arc */
        post: operations["ApiStoriesStoryIdArcsCreateArc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/arcs/{arc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an arc */
        get: operations["ApiStoriesStoryIdArcsArcIdGetArc"];
        put?: never;
        post?: never;
        /** Delete an arc */
        delete: operations["ApiStoriesStoryIdArcsArcIdDeleteArc"];
        options?: never;
        head?: never;
        /** Update an arc */
        patch: operations["ApiStoriesStoryIdArcsArcIdUpdateArc"];
        trace?: never;
    };
    "/api/arcs/{arc_id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stages in order */
        get: operations["ApiArcsArcIdStagesListStages"];
        put?: never;
        /** Add a stage */
        post: operations["ApiArcsArcIdStagesCreateStage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arcs/{arc_id}/stages/{stage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a stage */
        delete: operations["ApiArcsArcIdStagesStageIdDeleteStage"];
        options?: never;
        head?: never;
        /** Update a stage */
        patch: operations["ApiArcsArcIdStagesStageIdUpdateStage"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActCreate */
        ActCreate: {
            /** @default 1 */
            number: number;
            title?: string | null;
            summary?: string | null;
            emotional_shift_from?: string | null;
            emotional_shift_to?: string | null;
            opening_turning_point_id?: string | null;
            closing_turning_point_id?: string | null;
            /** @default 0 */
            sort_key: number;
        };
        /** ActOut */
        ActOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            /** Format: uuid */
            story_id: string;
            number: number;
            title: string | null;
            summary: string | null;
            emotional_shift_from: string | null;
            emotional_shift_to: string | null;
            opening_turning_point_id: string | null;
            closing_turning_point_id: string | null;
            sort_key: number;
        };
        /** ActUpdate */
        ActUpdate: {
            number?: number | null;
            title?: string | null;
            summary?: string | null;
            emotional_shift_from?: string | null;
            emotional_shift_to?: string | null;
            opening_turning_point_id?: string | null;
            closing_turning_point_id?: string | null;
            sort_key?: number | null;
        };
        /** ArcCreate */
        ArcCreate: {
            character_id?: string | null;
            relationship_id?: string | null;
            thread_id?: string | null;
            resolution?: string | null;
        };
        /** ArcOut */
        ArcOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            /** Format: uuid */
            story_id: string;
            character_id: string | null;
            relationship_id: string | null;
            thread_id: string | null;
            resolution: string | null;
        };
        /** ArcStageCreate */
        ArcStageCreate: {
            label: string;
            description?: string | null;
            /** @default 0 */
            sort_key: number;
        };
        /** ArcStageOut */
        ArcStageOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            /** Format: uuid */
            arc_id: string;
            label: string;
            description: string | null;
            sort_key: number;
        };
        /** ArcStageUpdate */
        ArcStageUpdate: {
            label?: string | null;
            description?: string | null;
            sort_key?: number | null;
        };
        /**
         * ArcType
         * @enum {string}
         */
        ArcType: "positive" | "negative" | "flat";
        /** ArcUpdate */
        ArcUpdate: {
            resolution?: string | null;
        };
        /**
         * AuthoringMode
         * @default hybrid
         * @enum {string}
         */
        AuthoringMode: "plotter" | "pantser" | "hybrid";
        /** BeatCreate */
        BeatCreate: {
            label: string;
            description?: string | null;
            act_id?: string | null;
            framework_position?: string | null;
            /** @default 0 */
            sort_key: number;
        };
        /** BeatOut */
        BeatOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            /** Format: uuid */
            story_id: string;
            act_id: string | null;
            label: string;
            description: string | null;
            framework_position: string | null;
            sort_key: number;
        };
        /** BeatUpdate */
        BeatUpdate: {
            label?: string | null;
            description?: string | null;
            act_id?: string | null;
            framework_position?: string | null;
            sort_key?: number | null;
        };
        /** CharacterCreate */
        CharacterCreate: {
            name: string;
            role?: components["schemas"]["CharacterRole"] | null;
            wound?: string | null;
            misbelief?: string | null;
            want?: string | null;
            need?: string | null;
            arc_type?: components["schemas"]["ArcType"] | null;
            voice_notes?: string | null;
        };
        /** CharacterOut */
        CharacterOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            /** Format: uuid */
            story_id: string;
            name: string;
            role: string | null;
            wound: string | null;
            misbelief: string | null;
            want: string | null;
            need: string | null;
            arc_type: string | null;
            voice_notes: string | null;
        };
        /**
         * CharacterRole
         * @enum {string}
         */
        CharacterRole: "protagonist" | "antagonist" | "mentor" | "foil" | "supporting";
        /** CharacterUpdate */
        CharacterUpdate: {
            name?: string | null;
            role?: components["schemas"]["CharacterRole"] | null;
            wound?: string | null;
            misbelief?: string | null;
            want?: string | null;
            need?: string | null;
            arc_type?: components["schemas"]["ArcType"] | null;
            voice_notes?: string | null;
        };
        /** CompletenessOut */
        CompletenessOut: {
            is_complete: boolean;
            missing: string[];
            required: string[];
            ratio: number;
        };
        /** EventCreate */
        EventCreate: {
            label: string;
            description?: string | null;
            /** @default 0 */
            sort_ordinal: number;
            display_label?: string | null;
            /** @default false */
            is_turning_point: boolean;
            /** @default false */
            is_on_page: boolean;
        };
        /** EventOut */
        EventOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            /** Format: uuid */
            story_id: string;
            label: string;
            description: string | null;
            sort_ordinal: number;
            display_label: string | null;
            is_turning_point: boolean;
            is_on_page: boolean;
        };
        /** EventUpdate */
        EventUpdate: {
            label?: string | null;
            description?: string | null;
            sort_ordinal?: number | null;
            display_label?: string | null;
            is_turning_point?: boolean | null;
            is_on_page?: boolean | null;
        };
        /** FindingOut */
        FindingOut: {
            code: string;
            level: number;
            severity: string;
            message: string;
            entity_type: string | null;
            entity_id: string | null;
        };
        /** HealthOut */
        HealthOut: {
            /** Format: uuid */
            story_id: string;
            max_level: number;
            warning_count: number;
            info_count: number;
            findings: components["schemas"]["FindingOut"][];
        };
        /** LadderOut */
        LadderOut: {
            /** Format: uuid */
            story_id: string;
            furthest_ready_level: number;
            levels: components["schemas"]["ReadinessOut"][];
            snapshot: components["schemas"]["SnapshotOut"];
        };
        /**
         * PovStyle
         * @enum {string}
         */
        PovStyle: "first" | "third_limited" | "third_omniscient" | "second" | "mixed";
        /** ReadinessOut */
        ReadinessOut: {
            level: number;
            label: string;
            is_ready: boolean;
            blocked_by: string[];
        };
        /** RelationshipCreate */
        RelationshipCreate: {
            /** Format: uuid */
            character_a_id: string;
            /** Format: uuid */
            character_b_id: string;
            history?: string | null;
            current_dynamic?: string | null;
            tension_notes?: string | null;
        };
        /** RelationshipOut */
        RelationshipOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            /** Format: uuid */
            story_id: string;
            /** Format: uuid */
            character_a_id: string;
            /** Format: uuid */
            character_b_id: string;
            history: string | null;
            current_dynamic: string | null;
            tension_notes: string | null;
        };
        /** RelationshipUpdate */
        RelationshipUpdate: {
            history?: string | null;
            current_dynamic?: string | null;
            tension_notes?: string | null;
        };
        /** ScaffoldOut */
        ScaffoldOut: {
            /** Format: uuid */
            story_id: string;
            framework: string;
            acts_created: number;
            beats_created: number;
            changed: boolean;
        };
        /** SnapshotOut */
        SnapshotOut: {
            story_is_complete: boolean;
            turning_point_count: number;
            character_count: number;
            complete_character_count: number;
            has_protagonist: boolean;
            act_count: number;
            complete_act_count: number;
            beat_count: number;
            complete_beat_count: number;
            thread_count: number;
            chapter_count: number;
            scene_count: number;
        };
        /** StoryCreate */
        StoryCreate: {
            title: string;
            premise?: string | null;
            genre?: string | null;
            pov_style?: components["schemas"]["PovStyle"] | null;
            structure_framework?: components["schemas"]["StructureFramework"];
            authoring_mode?: components["schemas"]["AuthoringMode"];
        };
        /** StoryOut */
        StoryOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            title: string;
            premise: string | null;
            genre: string | null;
            pov_style: string | null;
            structure_framework: string;
            authoring_mode: string;
            parent_story_id: string | null;
        };
        /** StoryUpdate */
        StoryUpdate: {
            title?: string | null;
            premise?: string | null;
            genre?: string | null;
            pov_style?: components["schemas"]["PovStyle"] | null;
            structure_framework?: components["schemas"]["StructureFramework"] | null;
            authoring_mode?: components["schemas"]["AuthoringMode"] | null;
        };
        /**
         * StructureFramework
         * @default three_act
         * @enum {string}
         */
        StructureFramework: "three_act" | "save_the_cat" | "custom";
        /** ThreadCreate */
        ThreadCreate: {
            type: components["schemas"]["ThreadType"];
            title?: string | null;
            owner_character_id?: string | null;
            /** @default 0 */
            sort_key: number;
        };
        /** ThreadOut */
        ThreadOut: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            completeness: components["schemas"]["CompletenessOut"];
            /** Format: uuid */
            story_id: string;
            type: string;
            title: string | null;
            owner_character_id: string | null;
            sort_key: number;
        };
        /**
         * ThreadType
         * @enum {string}
         */
        ThreadType: "a_story" | "b_story" | "c_story" | "throughline";
        /** ThreadUpdate */
        ThreadUpdate: {
            type?: components["schemas"]["ThreadType"] | null;
            title?: string | null;
            owner_character_id?: string | null;
            sort_key?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ApiHealthHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ApiStoriesListStories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"][];
                };
            };
        };
    };
    ApiStoriesCreateStory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdGetStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdDeleteStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdUpdateStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdHealthGetHealth: {
        parameters: {
            query?: {
                /** @description Only run rules at or below this level. */
                max_level?: number;
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdLadderGetLadder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LadderOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdScaffoldScaffold: {
        parameters: {
            query?: {
                /** @description Override the story's framework; additive, never destructive. */
                framework?: string | null;
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScaffoldOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdEventsListEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdEventsCreateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdEventsEventIdGetEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdEventsEventIdDeleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdEventsEventIdUpdateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdActsListActs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdActsCreateAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdActsActIdGetAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                act_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdActsActIdDeleteAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                act_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdActsActIdUpdateAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                act_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdBeatsListBeats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeatOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdBeatsCreateBeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeatCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeatOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdBeatsBeatIdGetBeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                beat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeatOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdBeatsBeatIdDeleteBeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                beat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdBeatsBeatIdUpdateBeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                beat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeatUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeatOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdThreadsListThreads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdThreadsCreateThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdThreadsThreadIdGetThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdThreadsThreadIdDeleteThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdThreadsThreadIdUpdateThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdCharactersListCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdCharactersCreateCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdCharactersCharacterIdGetCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdCharactersCharacterIdDeleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdCharactersCharacterIdUpdateCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdRelationshipsListRelationships: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdRelationshipsCreateRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdRelationshipsRelationshipIdGetRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdRelationshipsRelationshipIdDeleteRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdRelationshipsRelationshipIdUpdateRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdArcsListArcs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdArcsCreateArc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArcCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdArcsArcIdGetArc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                arc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdArcsArcIdDeleteArc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                arc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiStoriesStoryIdArcsArcIdUpdateArc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                arc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArcUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiArcsArcIdStagesListStages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcStageOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiArcsArcIdStagesCreateStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArcStageCreate"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcStageOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiArcsArcIdStagesStageIdDeleteStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arc_id: string;
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    ApiArcsArcIdStagesStageIdUpdateStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arc_id: string;
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArcStageUpdate"];
            };
        };
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArcStageOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
}
