"""Canonical starter outlines. These never copy another user's story or edits."""

from storytool.examples.blue_carbuncle import BLUE_CARBUNCLE
from storytool.examples.outline import Moment, StudyOutline

RED_HEADED_LEAGUE = StudyOutline(
    title="The Red-Headed League",
    premise="A pawnbroker's absurdly generous copying job hides a plan "
    "to tunnel into a bank vault.",
    genre="Detective short fiction · abridged study edition",
    pov_style="first",
    protagonist="Sherlock Holmes",
    pov_character="Dr. Watson",
    antagonists=("John Clay", "Archie"),
    chapter_titles=(
        "Wilson's strange employment",
        "The neighbouring bank",
        "The ambush",
        "Explaining the deception",
    ),
    voice_notes="Paraphrased study notes based on Conan Doyle's public-domain story. "
    "John Clay uses the alias Vincent Spaulding; Archie poses as Duncan Ross. "
    "The four chapters are an editorial outline, not original chapter divisions.",
    protagonist_want="Identify the purpose of the League and prevent the robbery",
    protagonist_need="Connect an apparently trivial complaint to its hidden danger",
    moments=(
        Moment(
            "Wilson brings his strange case to Holmes",
            70,
            "Investigation day · morning",
            "221B Baker Street",
            ("Sherlock Holmes", "Dr. Watson", "Jabez Wilson"),
            1,
            "Wilson describes a lucrative copying job that abruptly ended. Holmes suspects "
            "the peculiar arrangement served someone other than its red-haired employee.",
            turning=True,
        ),
        Moment(
            "Wilson is hired by the League",
            20,
            "Weeks before the investigation",
            "Pope's Court",
            ("Jabez Wilson", "John Clay", "Archie"),
            1,
            "Wilson recalls applying for the job after his assistant drew his attention "
            "to the advertisement. The supposed League secretary selects him.",
            True,
        ),
        Moment(
            "The copying job keeps Wilson away",
            30,
            "During the following weeks",
            "Pope's Court",
            ("Jabez Wilson",),
            1,
            "Wilson spends his mornings copying reference material under a rule that "
            "prevents him from leaving the office during work hours.",
            True,
        ),
        Moment(
            "The League closes without explanation",
            60,
            "Investigation day · before the visit",
            "Pope's Court",
            ("Jabez Wilson",),
            1,
            "Wilson finds a notice declaring the League dissolved. Unable to locate his "
            "employer, he seeks Holmes's help.",
            True,
            True,
        ),
        Moment(
            "Holmes inspects the pawnshop and its neighbour",
            72,
            "Investigation day · midday",
            "Saxe-Coburg Square",
            ("Sherlock Holmes", "Dr. Watson", "John Clay"),
            2,
            "Holmes taps the pavement, sees the assistant's worn trouser knees, and notices "
            "the bank behind the shop. The physical clues suggest underground work.",
            turning=True,
        ),
        Moment(
            "Holmes waits out the afternoon at a concert",
            74,
            "Investigation day · afternoon",
            "St James's Hall",
            ("Sherlock Holmes", "Dr. Watson"),
            2,
            "While Watson remains uncertain, Holmes listens to music with the confidence "
            "of someone who has already worked out the criminals' objective.",
        ),
        Moment(
            "The defenders wait inside the bank",
            88,
            "Investigation day · night",
            "City and Suburban Bank",
            ("Sherlock Holmes", "Dr. Watson", "Peter Jones", "Mr. Merryweather"),
            3,
            "Holmes brings the police and the bank director into the dark cellar. "
            "They wait near the gold for the thieves to emerge.",
        ),
        Moment(
            "Clay emerges from the tunnel and is caught",
            90,
            "Investigation day · late night",
            "City and Suburban Bank",
            (
                "Sherlock Holmes",
                "Dr. Watson",
                "John Clay",
                "Archie",
                "Peter Jones",
                "Mr. Merryweather",
            ),
            3,
            "Clay breaks through the cellar floor and is arrested. His accomplice retreats "
            "through the tunnel, where officers have been positioned. The gold remains safe.",
            turning=True,
        ),
        Moment(
            "The copying job's real purpose is revealed",
            10,
            "Before the League advertisement",
            "Wilson's pawnshop cellar",
            ("John Clay", "Archie"),
            4,
            "Holmes's explanation reconstructs the plan: the League was devised to get "
            "Wilson out of his shop while the thieves prepared a route to the bank.",
            True,
        ),
        Moment(
            "The thieves dig while Wilson copies",
            40,
            "During Wilson's employment",
            "Wilson's pawnshop cellar",
            ("John Clay", "Archie"),
            4,
            "The retrospective explanation places the tunnelling alongside Wilson's "
            "apparently harmless employment. Finishing the tunnel made the League unnecessary.",
            True,
        ),
        Moment(
            "Holmes explains the completed case to Watson",
            100,
            "After the arrests",
            "221B Baker Street",
            ("Sherlock Holmes", "Dr. Watson"),
            4,
            "The extravagant wages, the assistant's low pay, the cellar visits, and the "
            "sudden closure now form one coherent explanation.",
        ),
    ),
)

# Original, compact plot notes only: no Tolkien prose, dialogue, or copied chapter titles.
HOBBIT = StudyOutline(
    title="The Hobbit",
    premise="A home-loving hobbit joins a quest for a stolen homeland and learns to value "
    "courage and peace above possession.",
    genre="Fantasy · original study outline",
    pov_style="third_omniscient",
    protagonist="Bilbo Baggins",
    antagonists=("Smaug",),
    chapter_titles=(
        "Leaving a comfortable life",
        "Crossing into danger",
        "Unexpected resources",
        "Becoming the rescuer",
        "The dragon and the treasure",
        "Choosing peace",
    ),
    voice_notes="Original high-level study notes about Tolkien's novel, not its text. "
    "Chapter groupings and dramatic interpretations are editorial. "
    "Only selected major characters and events are represented.",
    protagonist_want="Help the company succeed and return safely home",
    protagonist_need="Trust his resourcefulness and choose compassion over greed",
    moments=(
        Moment(
            "Bilbo joins the dwarves' quest",
            10,
            "The quest begins",
            "Bag End",
            ("Bilbo Baggins", "Gandalf", "Thorin Oakenshield", "Balin"),
            1,
            "An unexpected company invites Bilbo to leave his comfortable home "
            "and help reclaim Erebor.",
            turning=True,
        ),
        Moment(
            "Smaug's earlier conquest explains the quest",
            0,
            "Years before the journey",
            "Erebor",
            ("Smaug", "Thorin Oakenshield"),
            1,
            "The dwarves recall losing their homeland and treasure to a dragon.",
            True,
        ),
        Moment(
            "Gandalf saves the company from trolls",
            20,
            "Early journey",
            "Troll clearing",
            ("Bilbo Baggins", "Gandalf", "Thorin Oakenshield"),
            2,
            "Bilbo's first attempt at burglary fails; Gandalf outwits the captors.",
        ),
        Moment(
            "Elrond interprets the map",
            30,
            "A pause in the journey",
            "Rivendell",
            ("Bilbo Baggins", "Gandalf", "Thorin Oakenshield", "Elrond"),
            2,
            "Hidden information reveals how the company might enter the mountain.",
        ),
        Moment(
            "Bilbo finds a ring and encounters Gollum",
            40,
            "Under the mountains",
            "Gollum's cave",
            ("Bilbo Baggins", "Gollum"),
            3,
            "Riddles and a mysterious ring help Bilbo escape; he spares Gollum.",
            turning=True,
        ),
        Moment(
            "The company finds refuge with Beorn",
            50,
            "After escaping the mountains",
            "Beorn's house",
            ("Bilbo Baggins", "Gandalf", "Thorin Oakenshield", "Beorn"),
            3,
            "The travellers recover before entering the forest without Gandalf.",
        ),
        Moment(
            "Bilbo rescues the dwarves from spiders",
            60,
            "The forest crossing",
            "Mirkwood",
            ("Bilbo Baggins", "Thorin Oakenshield", "Balin"),
            4,
            "Bilbo uses courage and invisibility to become his companions' rescuer.",
            turning=True,
        ),
        Moment(
            "Bilbo arranges an escape in barrels",
            70,
            "After elven imprisonment",
            "Elvenking's halls",
            ("Bilbo Baggins", "Thorin Oakenshield", "Balin"),
            4,
            "The company escapes confinement by travelling downriver hidden in cargo.",
        ),
        Moment(
            "Bilbo investigates the dragon's lair",
            90,
            "Arrival at the mountain",
            "Erebor",
            ("Bilbo Baggins", "Smaug"),
            5,
            "Bilbo discovers a weakness in Smaug's armour while confronting danger.",
        ),
        Moment(
            "Bard kills Smaug",
            100,
            "The dragon attacks",
            "Lake-town",
            ("Bard", "Smaug"),
            5,
            "The dragon dies, leaving survivors and dwarves with competing claims.",
            turning=True,
        ),
        Moment(
            "Bilbo offers the Arkenstone as leverage",
            110,
            "The dispute over treasure",
            "Camp outside Erebor",
            ("Bilbo Baggins", "Bard", "Thranduil"),
            6,
            "Bilbo risks Thorin's anger to create a chance for negotiation.",
            turning=True,
        ),
        Moment(
            "The rivals unite in battle",
            120,
            "A shared enemy arrives",
            "Battlefield outside Erebor",
            ("Bilbo Baggins", "Gandalf", "Thorin Oakenshield", "Bard", "Thranduil", "Beorn"),
            6,
            "A new threat turns competing factions into allies; victory carries losses.",
            turning=True,
        ),
        Moment(
            "Bilbo and Thorin reconcile",
            130,
            "After the battle",
            "Thorin's tent",
            ("Bilbo Baggins", "Thorin Oakenshield"),
            6,
            "A dying Thorin repairs their friendship and rejects his earlier greed.",
        ),
        Moment(
            "Bilbo returns home changed",
            140,
            "The return journey ends",
            "Bag End",
            ("Bilbo Baggins", "Gandalf"),
            6,
            "Bilbo returns with broader experience and a different relationship to comfort.",
        ),
    ),
)

STARTER_OUTLINES = (BLUE_CARBUNCLE, RED_HEADED_LEAGUE, HOBBIT)
