"""ai_connections_runs_observations_agent_tokens

Revision ID: 344a6443ea7d
Revises: 6c09a781e2bf
Create Date: 2026-10-07 13:05:06.487155

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '344a6443ea7d'
down_revision = '6c09a781e2bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        schema_upgrades()
        data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        data_downgrades()
        schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    op.alter_column('event', 'sort_ordinal', existing_type=sa.Integer(), nullable=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_connection',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('key_suffix', sa.String(length=4), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_ai_connection_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_connection')),
    sa.UniqueConstraint('user_id', 'provider', name='one_provider_per_user')
    )
    with op.batch_alter_table('ai_connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_connection_user_id'), ['user_id'], unique=False)

    op.create_table('ai_run',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('story_id', sa.GUID(length=16), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('applied_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inverse', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_ai_run_story_id_story'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_ai_run_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_run'))
    )
    with op.batch_alter_table('ai_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_run_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_run_user_id'), ['user_id'], unique=False)

    op.create_table('story_agent_token',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('story_id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_story_agent_token_story_id_story'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_story_agent_token_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_agent_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_story_agent_token_token_hash'))
    )
    with op.batch_alter_table('story_agent_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_agent_token_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_agent_token_user_id'), ['user_id'], unique=False)

    op.create_table('story_observation',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('story_id', sa.GUID(length=16), nullable=False),
    sa.Column('scene_id', sa.GUID(length=16), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_revision', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], name=op.f('fk_story_observation_scene_id_scene'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_story_observation_story_id_story'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_observation')),
    sa.UniqueConstraint('scene_id', 'source', name='one_observation_per_reader')
    )
    with op.batch_alter_table('story_observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_observation_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_observation_story_id'), ['story_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    op.execute('UPDATE event SET sort_ordinal = 0 WHERE sort_ordinal IS NULL')
    op.alter_column('event', 'sort_ordinal', existing_type=sa.Integer(), nullable=False)
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_observation_story_id'))
        batch_op.drop_index(batch_op.f('ix_story_observation_scene_id'))

    op.drop_table('story_observation')
    with op.batch_alter_table('story_agent_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_agent_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_story_agent_token_story_id'))

    op.drop_table('story_agent_token')
    with op.batch_alter_table('ai_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_run_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_run_story_id'))

    op.drop_table('ai_run')
    with op.batch_alter_table('ai_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_connection_user_id'))

    op.drop_table('ai_connection')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
