"""phase 1: levels 2-6

Revision ID: c60a56d39c40
Revises: adbe85c3f061
Create Date: 2026-10-04 23:13:49.454361

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    Bool,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    FernetBackend,
    JsonB,
    OneTimeCode,
    PasswordHash,
    StoredObject,
    TOTPSecret,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = (
    "data_downgrades",
    "data_upgrades",
    "downgrade",
    "schema_downgrades",
    "schema_upgrades",
    "upgrade",
)

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = "c60a56d39c40"
down_revision = "adbe85c3f061"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        schema_upgrades()
        data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        data_downgrades()
        schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("story_id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=True),
        sa.Column("wound", sa.Text(), nullable=True),
        sa.Column("misbelief", sa.Text(), nullable=True),
        sa.Column("want", sa.Text(), nullable=True),
        sa.Column("need", sa.Text(), nullable=True),
        sa.Column("arc_type", sa.String(length=20), nullable=True),
        sa.Column("voice_notes", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id"], ["story.id"], name=op.f("fk_character_story_id_story"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character")),
    )
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_character_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_character_story_id"), ["story_id"], unique=False)

    op.create_table(
        "event",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("story_id", sa.GUID(length=16), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_ordinal", sa.Integer(), nullable=False),
        sa.Column("display_label", sa.String(length=200), nullable=True),
        sa.Column("is_turning_point", sa.Boolean(), nullable=False),
        sa.Column("is_on_page", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id"], ["story.id"], name=op.f("fk_event_story_id_story"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_is_turning_point"), ["is_turning_point"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_event_story_id"), ["story_id"], unique=False)

    op.create_table(
        "act",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("story_id", sa.GUID(length=16), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("emotional_shift_from", sa.String(length=120), nullable=True),
        sa.Column("emotional_shift_to", sa.String(length=120), nullable=True),
        sa.Column("opening_turning_point_id", sa.GUID(length=16), nullable=True),
        sa.Column("closing_turning_point_id", sa.GUID(length=16), nullable=True),
        sa.Column("sort_key", sa.Float(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["closing_turning_point_id"],
            ["event.id"],
            name=op.f("fk_act_closing_turning_point_id_event"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opening_turning_point_id"],
            ["event.id"],
            name=op.f("fk_act_opening_turning_point_id_event"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["story.id"], name=op.f("fk_act_story_id_story"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_act")),
    )
    with op.batch_alter_table("act", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_act_story_id"), ["story_id"], unique=False)

    op.create_table(
        "relationship",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("story_id", sa.GUID(length=16), nullable=False),
        sa.Column("character_a_id", sa.GUID(length=16), nullable=False),
        sa.Column("character_b_id", sa.GUID(length=16), nullable=False),
        sa.Column("history", sa.Text(), nullable=True),
        sa.Column("current_dynamic", sa.Text(), nullable=True),
        sa.Column("tension_notes", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.CheckConstraint(
            "character_a_id <> character_b_id", name=op.f("ck_relationship_distinct_characters")
        ),
        sa.ForeignKeyConstraint(
            ["character_a_id"],
            ["character.id"],
            name=op.f("fk_relationship_character_a_id_character"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["character_b_id"],
            ["character.id"],
            name=op.f("fk_relationship_character_b_id_character"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["story.id"],
            name=op.f("fk_relationship_story_id_story"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship")),
    )
    with op.batch_alter_table("relationship", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_relationship_character_a_id"), ["character_a_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_relationship_character_b_id"), ["character_b_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_relationship_story_id"), ["story_id"], unique=False)

    op.create_table(
        "thread",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("story_id", sa.GUID(length=16), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("owner_character_id", sa.GUID(length=16), nullable=True),
        sa.Column("sort_key", sa.Float(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_character_id"],
            ["character.id"],
            name=op.f("fk_thread_owner_character_id_character"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["story.id"], name=op.f("fk_thread_story_id_story"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread")),
    )
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_thread_story_id"), ["story_id"], unique=False)

    op.create_table(
        "arc",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("story_id", sa.GUID(length=16), nullable=False),
        sa.Column("character_id", sa.GUID(length=16), nullable=True),
        sa.Column("relationship_id", sa.GUID(length=16), nullable=True),
        sa.Column("thread_id", sa.GUID(length=16), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(character_id is not null)::int + (relationship_id is not null)::int + (thread_id is not null)::int = 1",
            name=op.f("ck_arc_exactly_one_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
            name=op.f("fk_arc_character_id_character"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["relationship_id"],
            ["relationship.id"],
            name=op.f("fk_arc_relationship_id_relationship"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["story.id"], name=op.f("fk_arc_story_id_story"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["thread.id"], name=op.f("fk_arc_thread_id_thread"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_arc")),
    )
    with op.batch_alter_table("arc", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_arc_character_id"), ["character_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_arc_relationship_id"), ["relationship_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_arc_story_id"), ["story_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_arc_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "beat",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("story_id", sa.GUID(length=16), nullable=False),
        sa.Column("act_id", sa.GUID(length=16), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("framework_position", sa.String(length=80), nullable=True),
        sa.Column("sort_key", sa.Float(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["act_id"], ["act.id"], name=op.f("fk_beat_act_id_act"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["story.id"], name=op.f("fk_beat_story_id_story"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_beat")),
    )
    with op.batch_alter_table("beat", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_beat_act_id"), ["act_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_beat_story_id"), ["story_id"], unique=False)

    op.create_table(
        "arc_stage",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("arc_id", sa.GUID(length=16), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_key", sa.Float(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["arc_id"], ["arc.id"], name=op.f("fk_arc_stage_arc_id_arc"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_arc_stage")),
    )
    with op.batch_alter_table("arc_stage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_arc_stage_arc_id"), ["arc_id"], unique=False)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("arc_stage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_arc_stage_arc_id"))

    op.drop_table("arc_stage")
    with op.batch_alter_table("beat", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_beat_story_id"))
        batch_op.drop_index(batch_op.f("ix_beat_act_id"))

    op.drop_table("beat")
    with op.batch_alter_table("arc", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_arc_thread_id"))
        batch_op.drop_index(batch_op.f("ix_arc_story_id"))
        batch_op.drop_index(batch_op.f("ix_arc_relationship_id"))
        batch_op.drop_index(batch_op.f("ix_arc_character_id"))

    op.drop_table("arc")
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thread_story_id"))

    op.drop_table("thread")
    with op.batch_alter_table("relationship", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relationship_story_id"))
        batch_op.drop_index(batch_op.f("ix_relationship_character_b_id"))
        batch_op.drop_index(batch_op.f("ix_relationship_character_a_id"))

    op.drop_table("relationship")
    with op.batch_alter_table("act", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_act_story_id"))

    op.drop_table("act")
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_story_id"))
        batch_op.drop_index(batch_op.f("ix_event_is_turning_point"))

    op.drop_table("event")
    with op.batch_alter_table("character", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_character_story_id"))
        batch_op.drop_index(batch_op.f("ix_character_role"))

    op.drop_table("character")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
