"""phase 5: locations, scene location link, flashback flag

Revision ID: 93e68387feb8
Revises: a12dcbe6b3fc
Create Date: 2026-10-06 11:08:43.319299

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '93e68387feb8'
down_revision = 'a12dcbe6b3fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        schema_upgrades()
        data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        data_downgrades()
        schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('story_id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('atmosphere_notes', sa.Text(), nullable=True),
    sa.Column('sort_key', sa.Float(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_location_story_id_story'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location')),
    sa.UniqueConstraint('story_id', 'name', name='one_name_per_story')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_story_id'), ['story_id'], unique=False)

    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.GUID(length=16), nullable=True))
        batch_op.add_column(sa.Column('is_flashback', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index(batch_op.f('ix_scene_location_id'), ['location_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_scene_location_id_location'), 'location', ['location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_scene_location_id_location'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scene_location_id'))
        batch_op.drop_column('is_flashback')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_story_id'))

    op.drop_table('location')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
