"""phase 4: mentions and suggestions

Revision ID: 354e29feb656
Revises: cbc0b8215731
Create Date: 2026-10-05 21:32:13.855524

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '354e29feb656'
down_revision = 'cbc0b8215731'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        schema_upgrades()
        data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        data_downgrades()
        schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_character_mention',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('scene_id', sa.GUID(length=16), nullable=False),
    sa.Column('character_id', sa.GUID(length=16), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('is_rejected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_scene_character_mention_character_id_character'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], name=op.f('fk_scene_character_mention_scene_id_scene'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_character_mention')),
    sa.UniqueConstraint('scene_id', 'character_id', name='one_per_pair')
    )
    with op.batch_alter_table('scene_character_mention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_character_mention_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_character_mention_scene_id'), ['scene_id'], unique=False)

    op.create_table('suggestion',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('story_id', sa.GUID(length=16), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('character_id', sa.GUID(length=16), nullable=True),
    sa.Column('scene_id', sa.GUID(length=16), nullable=True),
    sa.Column('thread_id', sa.GUID(length=16), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('noticed_by', sa.String(length=20), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('fk_suggestion_character_id_character'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], name=op.f('fk_suggestion_scene_id_scene'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_suggestion_story_id_story'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name=op.f('fk_suggestion_thread_id_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestion')),
    sa.UniqueConstraint('story_id', 'code', 'character_id', 'scene_id', 'thread_id', name='one_per_subject')
    )
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_story_id'), ['story_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_story_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_code'))

    op.drop_table('suggestion')
    with op.batch_alter_table('scene_character_mention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_character_mention_scene_id'))
        batch_op.drop_index(batch_op.f('ix_scene_character_mention_character_id'))

    op.drop_table('scene_character_mention')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
