"""phase 2: chapters, scenes, join tables

Revision ID: 2b7834e6fca1
Revises: c60a56d39c40
Create Date: 2026-10-04 23:49:28.577432

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '2b7834e6fca1'
down_revision = 'c60a56d39c40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('story_id', sa.GUID(length=16), nullable=False),
    sa.Column('act_id', sa.GUID(length=16), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pov_character_id', sa.GUID(length=16), nullable=True),
    sa.Column('emotional_shift_from', sa.String(length=120), nullable=True),
    sa.Column('emotional_shift_to', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_key', sa.Float(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['act.id'], name=op.f('fk_chapter_act_id_act'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pov_character_id'], ['character.id'], name=op.f('fk_chapter_pov_character_id_character'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_chapter_story_id_story'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter'))
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_act_id'), ['act_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_story_id'), ['story_id'], unique=False)

    op.create_table('chapter_beat',
    sa.Column('chapter_id', sa.GUID(length=16), nullable=False),
    sa.Column('beat_id', sa.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beat.id'], name=op.f('fk_chapter_beat_beat_id_beat'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_chapter_beat_chapter_id_chapter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id', 'beat_id', name=op.f('pk_chapter_beat'))
    )
    op.create_table('scene',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('story_id', sa.GUID(length=16), nullable=False),
    sa.Column('chapter_id', sa.GUID(length=16), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('story_time_ordinal', sa.Integer(), nullable=True),
    sa.Column('time_label', sa.String(length=200), nullable=True),
    sa.Column('pov_character_id', sa.GUID(length=16), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('conflict', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('emotional_value_from', sa.String(length=120), nullable=True),
    sa.Column('emotional_value_to', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_key', sa.Float(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('fk_scene_chapter_id_chapter'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pov_character_id'], ['character.id'], name=op.f('fk_scene_pov_character_id_character'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_scene_story_id_story'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene'))
    )
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_story_id'), ['story_id'], unique=False)

    op.create_table('scene_arc_advance',
    sa.Column('scene_id', sa.GUID(length=16), nullable=False),
    sa.Column('arc_stage_id', sa.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['arc_stage_id'], ['arc_stage.id'], name=op.f('fk_scene_arc_advance_arc_stage_id_arc_stage'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], name=op.f('fk_scene_arc_advance_scene_id_scene'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_id', 'arc_stage_id', name=op.f('pk_scene_arc_advance'))
    )
    op.create_table('scene_beat',
    sa.Column('scene_id', sa.GUID(length=16), nullable=False),
    sa.Column('beat_id', sa.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beat.id'], name=op.f('fk_scene_beat_beat_id_beat'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], name=op.f('fk_scene_beat_scene_id_scene'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_id', 'beat_id', name=op.f('pk_scene_beat'))
    )
    op.create_table('scene_thread',
    sa.Column('scene_id', sa.GUID(length=16), nullable=False),
    sa.Column('thread_id', sa.GUID(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], name=op.f('fk_scene_thread_scene_id_scene'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name=op.f('fk_scene_thread_thread_id_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_id', 'thread_id', name=op.f('pk_scene_thread'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_thread')
    op.drop_table('scene_beat')
    op.drop_table('scene_arc_advance')
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_story_id'))
        batch_op.drop_index(batch_op.f('ix_scene_chapter_id'))

    op.drop_table('scene')
    op.drop_table('chapter_beat')
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_story_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_act_id'))

    op.drop_table('chapter')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
